name: Lines Of Code

on: [push]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update Badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: true
          directory: ./
          ignore: '.github|.gitbook.yaml|.gitignore|license|readme.md|security.md'
          badge: ./output/badge.svg
          badge_color: 'purple'
          badge_label: 'Lines Of Code'

      - name: Deploy to Badges branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: Badges
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
